"""Execute the actual embedded formatter against deterministic Linux fixtures."""
import contextlib
import io
import json
import os
import pathlib
import types
import unittest
from unittest.mock import patch

SOURCE = pathlib.Path(__file__).with_name('panel_cli.sh').read_text(encoding='utf-8')
CODE = SOURCE.split("<<'PYVIEW'\n", 1)[1].split('\nPYVIEW', 1)[0]


def render(view, width=72, preset='international', configurable=False, custom=False, baseline=False):
    presets = [
        dict(id='international', ipv4=['1.1.1.1', '1.0.0.1'], ipv6=['2606:4700:4700::1111', '2606:4700:4700::1001']),
        dict(id='mainland_china', ipv4=['223.5.5.5', '223.6.6.6'], ipv6=['2400:3200::1', '2400:3200:baba::1']),
    ]
    dns = dict(current=['8.8.8.8', '8.8.4.4'], current_source='/etc/resolv.conf',
               manager='systemd-resolved' if configurable else 'external', configurable=configurable,
               ipv6_available=True, presets=presets, reason='当前配置不支持由面板直接修改。',
               ipv4_probe_ok=True, ipv6_probe_ok=False, ipv6_skipped=False)
    files = {
        '/etc/os-release': 'PRETTY_NAME="Debian GNU/Linux 13 (trixie)"',
        '/proc/cpuinfo': 'model name : Intel Xeon E5-2697 v2 @ 2.70GHz',
        '/proc/meminfo': 'MemTotal: 2500000 kB\nMemAvailable: 1750000 kB\nSwapTotal: 1310720 kB\nSwapFree: 1310720 kB',
        '/proc/uptime': '89000 10',
        '/etc/resolv.conf': '# Generated by ctrl\nnameserver 8.8.8.8\nnameserver 8.8.4.4',
        '/etc/gai.conf': 'precedence ::ffff:0:0/96 100' if custom else '',
        '/etc/default/locale': 'LANG=en_US.UTF-8',
        '/etc/sysctl.d/99-ols-wpanel.conf': '# OLS WPanel — 网络与内核优化\nnet.core.somaxconn = 65535\nnet.ipv4.tcp_max_syn_backlog = 8192',
        '/etc/sysctl.d/.ols-wpanel-vps-original.json': json.dumps({'net.core.somaxconn':'65535','net.ipv4.tcp_max_syn_backlog':'8192'}) if baseline else '',
    }
    ticks = [0]

    def read(path, *args, **kwargs):
        key=path.as_posix()
        if key == '/proc/stat':
            ticks[0] += 1
            return f'cpu {100 + ticks[0]} 0 0 {1000 + ticks[0]*9} 0 0 0 0'
        return files.get(key, '')

    def command(args, **kwargs):
        output = ''
        if '--vps-tool' in args:
            if args[args.index('--vps-tool')+1] in ['dns-status','dns-test']: output=json.dumps(dns)
            else: output=json.dumps(dict(status='failed',stage='services',detail='service lshttpd did not become active: systemctl failed: exit status 4',updated_at='2026-10-02T08:54:54Z'))
        elif args[0]=='ip':
            family=6 if '-6' in args else 4
            output=json.dumps([{'addr_info':[{'local':'2001:db8::10' if family==6 else '192.0.2.10'}]}]) if '-j' in args else 'default via gateway'
        elif args[0]=='sysctl': output={'net.core.somaxconn':'65535','net.ipv4.tcp_max_syn_backlog':'8192','net.ipv4.tcp_congestion_control':'bbr','net.core.default_qdisc':'fq'}[args[-1]]
        elif args[0]=='date': output='2026-10-02 15:34:19 UTC'
        elif args[0]=='curl': output='ip='+('2001:db8::10' if '-6' in args else '192.0.2.10')
        elif args[0]=='apt': output='Listing...\nlinux-image-amd64/stable-security 6.12.111-1 amd64 [upgradable from: 6.12.107-1]'
        elif args[0]=='timedatectl': output='Timezone=UTC\nNTP=yes\nNTPSynchronized=no'
        elif args[0]=='systemctl': output='LoadState=loaded\nActiveState=active' if 'systemd-timesyncd.service' in args else 'LoadState=not-found'
        return types.SimpleNamespace(returncode=0, stdout=output, stderr='')

    out=io.StringIO();code=0;namespace={}
    with contextlib.ExitStack() as stack:
        stack.enter_context(patch.dict(os.environ, {'OLS_CLI_WIDTH':str(width)}))
        stack.enter_context(patch('sys.argv',['formatter',view,'panel','config',preset]))
        stack.enter_context(patch('pathlib.Path.read_text',read))
        stack.enter_context(patch('subprocess.run',command))
        stack.enter_context(patch('os.getloadavg',return_value=(.07,.04,0),create=True))
        stack.enter_context(patch('os.cpu_count',return_value=2))
        stack.enter_context(patch('os.path.isfile',return_value=baseline))
        stack.enter_context(patch('os.path.exists',return_value=False))
        stack.enter_context(patch('shutil.which',return_value='/usr/sbin/locale-gen'))
        stack.enter_context(patch('shutil.disk_usage',return_value=types.SimpleNamespace(total=43*1024**3,used=2*1024**3)))
        for key,val in [('node','demo-vps'),('release','6.12.107+deb13-amd64'),('machine','x86_64')]:stack.enter_context(patch('platform.'+key,return_value=val))
        stack.enter_context(patch('time.sleep'))
        stack.enter_context(contextlib.redirect_stdout(out))
        try:exec(compile(CODE,'embedded-cli','exec'),namespace)
        except SystemExit as e:code=e.code
    return out.getvalue(),code,namespace


class RendererTest(unittest.TestCase):
    def test_dns_separates_current_and_candidates(self):
        text,status,_=render('dns')
        self.assertEqual(status,2)
        self.assertIn('8.8.8.8\n',text)
        self.assertNotIn('1.1.1.1',text)
        self.assertIn('/etc/resolv.conf',text)
        self.assertIn('未读取到该类 DNS 地址',text)
        candidate,_,_=render('dns-preset')
        self.assertIn('候选地址',candidate)
        self.assertIn('2606:4700:4700::1111',candidate)
        self.assertNotIn('8.8.8.8',candidate)

    def test_no_raw_resolver_file_or_duplicate_resource_block(self):
        text,_,_=render('info')
        self.assertNotIn('Generated by',text);self.assertNotIn('nameserver',text)
        queues,status,_=render('queues')
        self.assertEqual(status,2)
        self.assertNotIn('CPU',queues);self.assertNotIn('Swap',queues)
        self.assertNotIn('重复',queues)
        self.assertEqual(render('queues',baseline=True)[1],0)

    def test_history_and_details_are_distinct(self):
        summary,_,_=render('updates');detail,_,_=render('update-details')
        self.assertIn('历史',summary);self.assertNotIn('exit status',summary)
        self.assertIn('exit status',detail)

    def test_custom_priority_rules_disable_changes(self):
        self.assertEqual(render('ip',custom=True)[1],2)

    def test_widths(self):
        for width in [48,72]:
            for view in ['info','dns','dns-preset','dns-test','ip','network','tuning','queues','queue-menu','updates','update-details','time','locale','clean']:
                text,_,ns=render(view,width)
                for line in text.splitlines():
                    self.assertLessEqual(ns['cells'](line),width,(view,width,line))

    def test_queue_menu_identifies_actual_values(self):
        text,status,_=render('queue-menu')
        self.assertEqual(status,2)
        self.assertIn('自定义 / 系统配置',text)
        self.assertIn('65535 / 8192',text)
        self.assertNotIn('安装器',text)
        self.assertNotIn('CPU',text)


if __name__=='__main__':unittest.main()
